### ISSUE TITLE
Crash on Camera View

### ISSUE THREAD

**Issue by georgera** [bitsy-ai/printnanny-os#277] opened 2023-02-22 22:26 UTC
## **Describe the bug**
Click on detections then click on camera view.  Crash comes up. 

## **To Reproduce**
What are the steps to reproduce the issue?
1. Go to 'PN Camera'
2. Click on Detection frame.
3. Click on Camera View frame.

system crash report comes up.

After submitting the crash report, "Submitting swizzle comes up and does nothing."

## **Expected behavior**
Clicking on detections and Camera view should do nothing.

## **Screenshots**
Please share screenshots to help explain your problem.

## Issue.txt
Copy and paste the contents of `issue.txt` below.
```
# paste issue.txt here
```

> ℹ️ You can find `/boot/issue.txt` on your SD card. You can also find the contents of `issue.txt` in OctoPrint's Settings > OctoPrint-Nanny > Report Issue tab.

**Comment by leigh-johnson** [comment] 2023-02-25 09:50
I'm going to close this for now. I couldn't reproduce in the current 0.6.5 build.
 
I have a hunch that you were experiencing a lot of unusual failures due to an invalid API token. Can you please re-open and submit a crash report if this happens again? Thank you! 🙇‍♀️

**Closed by leigh-johnson** 2023-02-25 09:50 UTC
Labels: bug
